services:
  backend:
    image: eyapa/eyegazeheatmap:backend_v1
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./backend/data:/app/data
      - ./backend/db:/app/db

  frontend-local:
    profiles: ["local"]
    build:
      context: ./frontend
      args:
        - VITE_CONFIG_FILE=vite.local.ts
        - NGINX_CONFIG_FILE=nginx.local.conf
    image: eyapa/eyegazeheatmap:frontend_local
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - eyegaze-net
    volumes:
      - ./frontend/nginx.local.conf:/etc/nginx/conf.d/default.conf:ro
    

  frontend-global:
    profiles: ["global"]
    build:
      context: ./frontend
      args:
        - VITE_CONFIG_FILE=vite.global.ts
        - NGINX_CONFIG_FILE=nginx.global.conf
    image: eyapa/eyegazeheatmap:frontend_global
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - DOLLAR='$'
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - eyegaze-net

networks:
  eyegaze-net:
    driver: bridge