services:
  backend:
    image: eyapa/eyegazeheatmap:backend_v1
    env_file:
      - ./.env
    volumes:
      - ./backend/data:/app/data
      - ./backend/db:/app/db
    networks:
      - eyegaze-net
    restart: always

  frontend-local:
    profiles: ["local"]
    image: eyapa/eyegazeheatmap:frontend_local
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - eyegaze-net
    restart: always

  frontend-global:
    profiles: ["global"]
    image: eyapa/eyegazeheatmap:frontend_global
    env_file:
      - ./.env
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUBLIC_IP=${PUBLIC_IP}
      - DOLLAR=$$
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - backend
    networks:
      - eyegaze-net
    restart: always

networks:
  eyegaze-net:
    driver: bridge